### ISSUE TITLE
Put a legend on the trip information map

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#168]
There are a lot of colors flying around -- blue and red for inbound/outbound stops, red/green for start/end stops. Can we add that to the legend (which just shows speed colors right now)?

![Screenshot 2019-07-10 at 8 50 01 PM](https://user-images.githubusercontent.com/728084/61020947-516a1d80-a354-11e9-9744-c75436a95c73.png)

**Comment by juanmanual** [comment]
#173

**Comment by exxonvaldez** [comment]
Just a note that a lot of the colors in the UI are effectively placeholders — they wouldn’t pass muster in terms of accessibility for color blind users, and we don’t have a proper visual hierarchy set up.  I’m not sure we need different colors for inbound and outbound stops (Routesy app and Nextbus app don’t do this).

**Comment by hathix** [comment]
Agree, I don't think we need the different inbound/outbound colors. What should we do for start/end stops (which we will probably need to keep marking)?

**Comment by juanmanual** [comment]
If the start/end stop colors change I would recommend making them different than the speed colors (red/green), since it will be confusing to have two legends on the same map that show different meanings for the same color.

**Comment by exxonvaldez** [comment]
The speed colors are from Google Maps (live traffic).  I tried various color palettes from D3, but for me the green/yellow/red scheme is the only one that seemed intuitive, because it is so common.

I  noticed that Google Maps shows traffic along a driving route.  The start and end points are marked with shapes.  An open black circle at start, then dotted black circle and marker icon at end. Both with text labels.  Those text labels are the only bold black text on the map, and the circles are the only black shapes.  These are reinforced by the lefthand sidebar (not shown) which uses the same shapes.  Seems like a good model to copy, and we could put whatever shapes/symbols we use next to the stop picker dropdowns also.

![Screen Shot 2019-07-11 at 4 24 59 PM](https://user-images.githubusercontent.com/44861283/61091831-82039300-a3f8-11e9-9861-1d7837968f3c.png)

**Comment by hathix** [comment]
Someone started this in #173, but it hasn't been touched in a while. Someone else is welcome to finish this.

**Comment by exxonvaldez** [comment]
Marking as closed as we shouldn't need a legend now after #330.
