### ISSUE TITLE
Making rating system accessible

### ISSUE THREAD

**Issue by exxonvaldez** [trynmaps/metrics-mvp#197]
In #176 we are using colored backgrounds to show the quartiles of scores (instead of the placeholder A/B/C/D we had before).  This is not fully accessible for color blind users, so we should use something like https://material-ui.com/components/rating/ (on a scale of 1 to 4 stars, or switch to pentiles for 5 stars) or a set of 4 icons or symbols to represent the quartiles.  Alternatively, we could have a graphical indicator of score, such as a "partial ring" around the score or a tiny horizontal bar that is partially filled in.

Another thing that can be split out as another issue:  The scores need some way of showing how they were calculated, possibly a Material UI Popper widget.

**Comment by hathix** [comment]
I see that your PR #176 adds stars. Very nice!

![Screenshot 2019-07-24 at 6 30 21 PM](https://user-images.githubusercontent.com/728084/61839108-221ddb00-ae41-11e9-85ef-c48f11d9724b.png)

 Couple small concerns:

* The yellow stars might blend into the background of yellow cards. In this case, it's hard to tell which stars are filled in and which ones aren't.
* The Median Wait star rating is a bit confusing -- at first glance it looks like it has 5 stars, but on closer inspection you realize it's 0/5.

Perhaps we could just color the score or big number, instead of coloring the card? Or do some other treatment of the stars?

**Comment by exxonvaldez** [comment]
Proposed fix:  adjust yellow to get more contrast with the stars.  Also make the minimum star rating 0.5 stars rather and zero stars so that the rating widget is never completely empty.

<img width="639" alt="Screen Shot 2019-09-18 at 8 25 46 PM" src="https://user-images.githubusercontent.com/44861283/65211162-909ea400-da52-11e9-81de-95d4c9d11cfb.png">
