### ISSUE TITLE
Finish #173 (map stop legend)

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#291]
Some random person started PR #173 but never finished it. I'm just making this Issue to remind everyone we need to finish it.

**Comment by exxonvaldez** [comment]
We discussed how Google Maps doesn't need a legend, and we could use that as a model so that we don't need to add a stop legend.  Changes we would need to get there:

- make all stops the same color
- select icons similar to what google maps uses for start and end
- put these icons next to the start and end stop dropdowns

**Comment by exxonvaldez** [comment]
Also this issue overlaps with #168.

**Comment by exxonvaldez** [comment]
Fixed by #330.
