### ISSUE TITLE
to enable or not to enable cors

### ISSUE THREAD

**Issue by mjrerle2** [trynmaps/metrics-mvp#30]
should we enable cors?

this involves:

- flask cors being functional
- js cors being functional
- security concerns (which methods should we make public and stuff)

**Comment by hathix** [comment]
For the MVP I don't think CORS is necessary, but once we scale up we should enable it.

**Comment by youngj** [comment]
https://github.com/trynmaps/metrics-mvp/pull/49 enables CORS for all domains so that the development React frontend can be on a different port than the Flask backend. Since the backend currently only supports unauthenticated stateless GET requests, I don't see a security concern with allowing CORS from any domain.
