### ISSUE TITLE
Implement date ranges

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#301]
This way users could see the average speed/wait time/etc for longer time ranges. Currently they can only see one day's data at a time, which doesn't really let them understand macro trends.

Requires a ton of backend work because we have to port everything else we do to handle averages over the days.

**Comment by exxonvaldez** [comment]
Jesse notes that we should use @jtanquil 's Graph QL PR to build our date range support for the metrics the API.

**Comment by SeannyPhoenix** [comment]
What about letting users select multiple days, such as all Mondays for the last month?

**Comment by exxonvaldez** [comment]
Yes, we want to do that also.  We have a model for the UI in #78 .  But to start, this issue is just about basic date range support and just for the stop-to-stop data.

**Comment by exxonvaldez** [comment]
I should also mention the bigger vision that @youngj has for what we call the "precomputed" files is like a server-based caching service.  We have wait and travel time data for each day precomputed as json files, and the cache would serve up aggregate versions of these files over arbitrary date ranges.  This issue should be broken up into a couple of smaller issues.

**Comment by exxonvaldez** [comment]
The precomputed files are used for the isochrone, and the route-level stats.

**Comment by youngj** [comment]
@hathix @exxonvaldez @wllgrnt @Eochs I'm thinking the GraphQL schema could look something like this:

```
type TripMetrics {    
    byDay(
        startDate: String
        endDate: String
        startTime: String
        endTime: String
    ): [BasicIntervalMetrics]
    
    # existing `interval` field is unchanged
}

type BasicIntervalMetrics {
    startDate: String 
    endDate: String  # for now each BasicIntervalMetrics would only include one date, so startDate == endDate, but later tripMetrics could have byWeek or byMonth fields where startDate != endDate
    startTime: String
    endTime: String
    waitTimes: BasicWaitTimeStats
    tripTimes: BasicTripTimeStats
}

type BasicWaitTimeStats {
    median: Float
    percentile(percentile: Int!): Float
    probabilityLessThan(minutes: Int!): Float
}

type BasicTripTimeStats {
    median: Float
    percentile(percentile: Int!): Float
}
```

Then the client could make a query like this to fetch precomputed wait time / trip time stats for a particular trip over a range of dates:

```
query {
  routeMetrics(routeId:"1") {
    trip(startStopId:"4015", endStopId:"6304") {
      byDay(startDate:"2019-10-11", endDate:"2019-10-15", startTime:"07:00", endTime:"10:00") {
        waitTimes {
          median
          p10: percentile(percentile:10)
          p50: percentile(percentile:50) # same as median
          p90: percentile(percentile:90)
          plt5m: probabilityLessThan(minutes:5)
          plt20m: probabilityLessThan(minutes:20)
        }
        tripTimes {
          median
          p10: percentile(percentile:10)
          p50: percentile(percentile:50) # same as median
          p90: percentile(percentile:90)
        }
      }
    }
  }
}
```

The query would return an array of BasicIntervalMetrics objects - the frontend could extract the values it needs from each object, make arrays out of those values and draw them as a line/bar chart. The API assumes the frontend will only need time-series data for one stop or pair of stops at a time. Would this API provide what is necessary to implement the planned features on the frontend? 

This could be implemented by adding to the schema in models/schema.py .

To look up a precomputed stat for a particular date, could call get_cached_wait_times (from models/wait_times.py) or get_cached_trip_times (from models/trip_times.py) then call the `get_value` method to get the precomputed stat for the requested stop or stops. 

Could return an error if the parameter does not correspond to a precomputed stat (e.g. 30th percentile, or a time range like 07:00 - 08:00). Alternatively, could just compute the value from the arrival times for each date using the same approach as WaitTimeStats / TripTimeStats. Would be interesting to compare the speed of recomputing stats for each day compared to loading precomputed stats.

How do you think this would work? Does anyone have time to work on this in the next few days?

**Comment by exxonvaldez** [comment]
Hi @youngj , thanks for writing up this level of detail.  Just for everybody's reference, there is a super rough UI sketch here:  https://docs.google.com/document/d/17I9-LRN1TLD0KIFP5a-jI_VVnO3ydgzbwj1_tYKpe1w/edit?usp=sharing and an issue for the date picker ui at #78.

The Uber UI is limited to a 90 day range, I assume we would have a similar limit.

I like your idea of generalizing to other time units like week and month.  I thought the Uber UI also had hardcoded historic date ranges (like, quarters of the previous year), but I don't see those now.
 
 One thing about the existing graphQL query is that @wllgrnt told me it takes a list of days (`interval(dates:[$date]`), but here you specified start and end dates.  Given that we want to support fairly complex date specifications (e.g., only weekdays between date X and date Y, or only Mondays and Fridays), I like the list of days because it is more flexible.   Or else the query itself would have to support options like which days of the week to include.

The screen we're working on first is the stop-to-stop screen, and the API you sketched out sounds great for adding time series charts to the stop-to-stop screen.  At some later point, we'll have to figure out how we're doing time series for a route (for the route level summary) and/or aggregrate stats for all routes (for the route table).  We could use the same API for the route summary and using the terminals as start and end, with some tweaks to deal with routes where the last stop isn't always reached.  But that won't work for the route table.

**Comment by youngj** [comment]
Thanks for the feedback. Updating `byDay` to take a list of date strings (like `interval`) sounds good to me.

**Comment by hathix** [comment]
Jesse, is the Portland team owning this?

**Comment by youngj** [comment]
Yes @Eochs is currently working on the GraphQL API for this, but we're currently not planning to work on the frontend.
