### ISSUE TITLE
Picking a future date generates a non-user-friendly error

### ISSUE THREAD

**Issue by SeannyPhoenix** [trynmaps/metrics-mvp#336]
![Screenshot 2019-10-16 20 12 02](https://user-images.githubusercontent.com/12836949/66974832-4c9ebf00-f051-11e9-8eab-cb0837473396.png)

Selecting a future date in the Isochrone generates a browser alert with the following message:
error loading wait times: Invalid JSON

**Comment by hathix** [comment]
I get "Error: "Request failed with status code 404" instead of that alert

**Comment by amadigan** [comment]
<img width="1473" alt="Screen Shot 2019-10-16 at 8 36 15 PM" src="https://user-images.githubusercontent.com/700311/66975921-dc923800-f054-11e9-87ee-d16d1b4dd9d4.png">

It looks like it's fetching JSON from an S3 bucket, which is returning an (XML) forbidden response. I'm guessing this will have to be fixed in the frontend.

**Comment by SeannyPhoenix** [comment]
Working on the frontend to prevent users from selecting invalid dates.

**Comment by hathix** [comment]
We also need to make sure this fix works on browsers that don't support the fancy calendar-like datepicker, like Safari. See #341.
