### ISSUE TITLE
Fix confusing "90% of trips" card

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#382]
When you choose a trip with a to & from stop selected ([example](https://muni.opentransit.city/route/L/direction/L____I_F00/fromStop/5726/toStop/5417)), you get this weird "90% of trips" card. It's confusing.

<img width="700" alt="Screen Shot 2019-11-06 at 6 07 41 PM" src="https://user-images.githubusercontent.com/728084/68354197-8d25b180-00c0-11ea-9a0b-4e26796598e6.png">

Instead, we should:

* Put the average trip card first, since that's what people are interested in knowing
* Call "90% of trips" the "worst case" and explain somewhere (in a tooltip?) that it represents the 90th percentile of trips

**Comment by exxonvaldez** [comment]
"worst case" is not accurate to say since 10% of the trips have longer wait and travel times.

NYC bus stats had a bar graph for this that was labeled "planning" (along with "average").  http://www.busstat.nyc/routes/BX41 .  They don't actually define what "planning" is on that screen, but on the Methodology page they mention 95% percentile.  http://www.busstat.nyc/methodology

**Comment by exxonvaldez** [comment]
How about titling the card "Most Trips Under 52 min" and add an info button that says "90% of trips took this much time or less".

Also regarding #392 and SFMTA feedback, we can rename "Extra Travel" to "Travel Variance" as that is the standard term (and add text to the info icon popup, saying "Variance is the travel time beyond the median time (for 90% of the trips)."

**Comment by exxonvaldez** [comment]
#417 addressed some of this.  Now instead of "90% of trips" problem, we have the "journey planning" problem #435.  Closing this issue in favor of that issue.
