### ISSUE TITLE
Speed calculations should be based on distance between stops used in trip time calculations

### ISSUE THREAD

**Issue by youngj** [trynmaps/metrics-mvp#407]
The function getSpeedAndVariabilityForRoute calculates "median speed" by dividing `distance.direction` by the median trip time between two stops at or near the ends of the route. However, the distance between these two stops may be smaller than `distance.direction`, resulting in incorrect speed calculations.

**Comment by exxonvaldez** [comment]
Good catch.  I am responsible for the non-straightforward nature of this computation due to the added logic for skipping of first/last stops, or ranges of stops.  I will outline the fix here and may pick this up in a bit.  I want to get #78 (UI for date ranges) started first.

The call tree is (all functions in routeCalculations.js):

* `getSpeedAndVariabilityForRoute`
   * `getEndToEndTripTime`
      * `getTripTimesUsingHeuristics`


The innermost function chooses a start stop and gets the trip times for it.  This function needs to also return the distance of this stop along the route (`direction.stop_geometry[firstStop].distance`), or some way for the caller to get this distance.

The middle function chooses an end stop and gets the trip time to it from the start stop.  This function needs to return the distance along the route between the start and end stops, or some way for the caller to get this distance.

Finally, the outer function gets times for the different directions and needs to use the "start stop" to "end stop" distance instead of `direction.distance` to compute speeds.

Caution: The middle and inner functions are also used by the `TravelTimeChart` component to display the full travel time and generate the data series for the chart, respectively.
