### ISSUE TITLE
Fix oversized date/time box in the top right

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#431]
In some situations, the gray date/time box on the top right gets way too big:

<img width="1234" alt="Screen Shot 2019-11-20 at 6 34 28 PM" src="https://user-images.githubusercontent.com/728084/69299704-11e6f400-0bc6-11ea-8ea7-17115a4dfeb2.png">

Not sure when this happens, but we should make sure we avoid it.

**Comment by exxonvaldez** [comment]
I am fixing this in #321 , where I am making room for a second date range in the app bar.

**Comment by exxonvaldez** [comment]
This is now fixed by #415 , which moved most of the bread crumb to a new Paper area just below the blue app bar.  This lets the bread crumb wrap as needed on small screens without affecting the layout of the date picker (and bunching up against it).

![Screen Shot 2019-11-26 at 12 06 29 AM](https://user-images.githubusercontent.com/44861283/69610516-d5116780-0fe0-11ea-8934-ffe5c716f310.png)
