### ISSUE TITLE
Fix bug with loading GraphQL query URL in Graphiql

### ISSUE THREAD

**Issue by akgupta89** [trynmaps/metrics-mvp#485]
I can't seem to use the graphiql at the expected url of localhost:3000/api/graphiql or localhost:3000/graphiql and there is no mention of it in the documentation. To support our graphql conversion and make development easier we need to push for this and make it easily accessible.

**Comment by youngj** [comment]
When graphiql is enabled on /api/graphql , I ran into a problem where opening a graphql URL in the browser fails due to a script error (e.g. right clicking the URL in Chrome's Network tab -> open in new tab). This makes it difficult to debug GraphQL queries. Instead of just enabling graphiql at /api/graphql (which is weird because it replaces the actual GraphQL API with a web UI if you open the URL in a browser), I think it would be better to configure a frontend route like /graphql to show the web UI, so that /api/graphql can just be a normal API regardless of the User-Agent.

**Comment by akgupta89** [comment]
Ah so it runs on /api/graphql, looks like port 5000 only. Looks like rerouting the URL isn't natively supported yet by the app. I need to work on the twitter bot stuff but I can look into rerouting the url later.
