### ISSUE TITLE
Add "apply"/"done" button to date picker

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#550]
Currently it's not obvious how you "apply" any changes you made to the date range dropdown. The changes actually happen immediately, but it's a bit jarring because you're not sure exactly how to exit the dropdown. In my head, I was thinking "if I hit X or click outside the dropdown, will it reset my changes?" 

![Screen Shot 2020-02-12 at 8 37 33 PM](https://user-images.githubusercontent.com/728084/74401904-8ac9a680-4dd7-11ea-88fe-641d2d2f3f7e.png)

Now, obviously my gut reaction wasn't accurate, but it still shows that UX is confusing. We could use an "Apply" or "Done" button that literally just closes the popup but gives the user peace of mind.

My comment in #461 shows some random bugs that could be fixed by this.

We can copy Uber Movement for this. I think Uber movement doesn't have a reset button, just a Done button.

**Comment by hathix** [comment]
Here's what Uber movement does. 

![Screen Shot 2020-02-12 at 8 40 51 PM](https://user-images.githubusercontent.com/728084/74402056-ff044a00-4dd7-11ea-820f-83e2d711cd14.png)

**Comment by exxonvaldez** [comment]
With #461, the "x" turned into an "apply" button.  But it's better to copy Uber and add a more explicit "apply" button.  "x" then becomes "ignore my changes".

There is also a separate bug to fix here where the second date range cannot be "yesterday".  That is because it looks like the default date range and doesn't make it into the query string (we have logic to filter out default values, to make the query string as short as possible).  The fix is to add another flag to redux indicating whether the second date range is active or not.
