### ISSUE TITLE
timetable data missing for many stops on each route

### ISSUE THREAD

**Issue by jtanquil** [trynmaps/metrics-mvp#67]
The 311.org API only provides timetables for a portion of the stops on each route. Without a timetable to compare actual arrival times to, it will be more difficult to evaluate how close buses are keeping on schedule at a particular stop. If we can't get this information from another source, here are a few possible workarounds:

- for each route, SFMTA gives projected service frequencies, as well as the first and last trip for each day of the week (ex/ https://www.sfmta.com/routes/10-townsend). For any stop whose timetable isn't on 311, we can just use this information to generate a projected timetable. This would be simple, but I suspect it wouldn't be very accurate.

- given the timetables that we already have access to, we could interpolate the timetables for the other stops by adding the projected time between stops to the stop with a known timetable. Since stops are different distances from each other, this feels like it would produce more accurate timetables, but I don't know how we would obtain the projected time between stops - using the data we have now doesn't make sense since what we want to do is compare that data to what is projected, as opposed to comparing the data to itself.

**Comment by EddyIonescu** [comment]
Schedule information can be found in GTFS (https://www.sfmta.com/reports/gtfs-transit-data). the `stop_times` file contains a list of all the trips that serve each stop. We could also use this library (https://github.com/remix/partridge) to parse it.

That said, for frequent routes (I'd go with every 20 minutes or better), it might be better to be headway-based rather than schedule-based, as no one really pays attention to the schedule in those cases anyways. 

Unfortunately I couldn't find any documents containing the headways for each route/service period, so the only way of getting this would be either inferring from the GTFS, manually entering it for each route from its webpage, or requesting it from the SFMTA (I can look into doing that).

**Comment by hathix** [comment]
For our purposes, we just want to understand the expected time between buses, not the exact moment the buses arrive. So I think using GTFS schedules works even for high-frequency routes, since we're just trying to get a feel for the expected time between buses.

Jose mentioned today that he's playing around with GTFS & Partridge... will keep this issue updated.
