### ISSUE TITLE
Make the /metrics endpoint not monolithic

### ISSUE THREAD

**Issue by hathix** [trynmaps/metrics-mvp#93]
Currently, in `metrics-api.py`, the `/metrics` endpoint is an unholy giant function. Can we separate that into separate smaller functions  (or at least pull out some code into helper functions)?

**Comment by jtanquil** [comment]
In general, would it also be a good idea to split up the data that `\metrics` and `\metrics_by_interval` (when that gets merged) return into separate endpoints for each metric? Maybe having `\metrics\wait_times`, `\metrics\travel_times` and `\metrics\headways` be the endpoints and implement functionality in each of those endpoints to support returning data from multiple time intervals? It would make the api a bit easier to work with, although the frontend would have to change accordingly.

**Comment by hathix** [comment]
That's a good idea because it reduces the size of that mega-function and also lets us pick and choose which graphs to show in different places (e.g. imagine we have a stripped-down view that only shows one graph -- in which case it's much better to have separate endpoints for each metric than one giant endpoint that sends data the view doesn't need).

**Comment by youngj** [comment]
I'm working on a PR that refactors the /metrics endpoint to make the code more maintainable and easier to reuse when calculating metrics for different date/time intervals without reloading arrival history.

It keeps /metrics as one API endpoint in order to avoid loading data separately for each metric (which will get slower when we implement date ranges). It separates calculations for wait times, trip times, and headways into their own methods and allows computing those statistics for different date/time ranges and returning different data for each (e.g. avg, percentiles, histogram)

Wait times, trip times, and headways shouldn't be split into multiple API endpoints because that would require the backend to load the arrival history and build a data frame for each type of metric it want to calculate, instead of just once. Once we implement date ranges this will be an even bigger issue. The /metrics_by_interval API endpoint should eventually be merged with the /metrics API for this reason.

There could be parameters on the /metrics API that specify which stats to return, or we could use GraphQL . I'm not planning to address that in my PR but someone could work on that after.

**Comment by jtanquil** [comment]
@youngj i've been working on a similar PR, although currently it splits up /metrics into multiple endpoints - https://github.com/jtanquil/metrics-mvp/tree/refactor-metrics-api

Since defining the endpoints in metrics-api was redundant maybe something like

`@app.route('/metrics/<stat>', methods = ['GET'])`

could work, where `stat` is just the metrics or list of metrics that the user wants to return.

**Comment by hathix** [comment]
Jose is actively working on this

**Comment by hathix** [comment]
#334 fixed this
